GET http://localhost:3000/players/

###
POST http://localhost:3000/players/
Content-Type: application/json

{
  "playerName": "Tomrys",
  "jerseyNumber":78,
  "role": "Allrounder"
}

###
GET http://localhost:3000/players/1/
###
PUT http://localhost:3000/players/9/
Content-Type: application/json

 {
  "playerName": "Maneesh",
  "jerseyNumber": 55,
  "role": "All-rounder"
}

###
DELETE http://localhost:3000/players/13/
